"""empty message

Revision ID: 2de6f7197b73
Revises: 62cdcf84746b
Create Date: 2024-08-07 01:43:40.327891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de6f7197b73'
down_revision = '62cdcf84746b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_events_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_events_url'), ['url'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_events_url'))
        batch_op.drop_index(batch_op.f('ix_shared_events_event_id'))

    op.drop_table('shared_events')
    # ### end Alembic commands ###
