"""empty message

Revision ID: 4d3049de25e8
Revises: 3c659d90c739
Create Date: 2024-07-24 02:12:39.827179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3049de25e8'
down_revision = '3c659d90c739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('armor', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('speed', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('firepower', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('dps', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('heatsinks', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('dissipation', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builds', schema=None) as batch_op:
        batch_op.drop_column('dissipation')
        batch_op.drop_column('heatsinks')
        batch_op.drop_column('dps')
        batch_op.drop_column('firepower')
        batch_op.drop_column('speed')
        batch_op.drop_column('armor')

    # ### end Alembic commands ###
