"""empty message

Revision ID: 62cdcf84746b
Revises: 4d3049de25e8
Create Date: 2024-07-25 17:26:25.224008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cdcf84746b'
down_revision = '4d3049de25e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=True, default=0))

    op.execute('UPDATE users SET role = 2 WHERE admin')
    op.execute('UPDATE users SET role = 1 WHERE role is NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
